---
apiVersion: v1
kind: Service
metadata:
  name: image
spec:
  selector:
    app: "image-app-pods"
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9527
---
#apiVersion: extensions/v1beta1
#kind: Deployment
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "image-app-pods"
  template:
    metadata:
      labels:
        app: "image-app-pods"
        purpose: "service-test"
    spec:
      containers:
      - name: "image-app"
        image: beekman9527/inceptionserver:lit
        args:
        - --v=3
        - --imgdir=/tmp/imgs/ 
        resources:
          limits:
            cpu: "990m"
          requests:
            cpu: "200m"
        ports: 
        - containerPort: 9527

